#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$KEYCLOAK_INIT_USER" WITH PASSWORD '$KEYCLOAK_INIT_PASS';
  CREATE DATABASE "$KEYCLOAK_INIT_DB";
  GRANT ALL PRIVILEGES ON DATABASE "$KEYCLOAK_INIT_DB" TO "$KEYCLOAK_INIT_USER"
EOSQL
