# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI tests with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Create DB
        run: |
          sudo -u postgres createdb adventureit
          sudo -u postgres psql --command="CREATE USER adventure_user PASSWORD 'adventure_password'" --command="\du"

      - name: Run SQL
        run: sudo -u postgres psql -d adventureit -a -f env/postgres/db_scripts/adventureit.sql

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run micro-adventure
        run: |
          chmod +x ./micro-adventure/mvnw
          ./micro-adventure/mvnw spring-boot:start

      - name: Run micro-user
        run: |
          chmod +x ./micro-user/mvnw
          ./micro-user/mvnw spring-boot:start

      - name: Build with Maven
        run: |
          chmod +x mvnw
          mvnw -B package --file pom.xml
